//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormAppProje.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Öğrenciler
    {
        public int ID { get; set; }
        public string İsim { get; set; }
        public string Soyisim { get; set; }
        public string Telefon { get; set; }
        public string TCkimlik { get; set; }
    }
}
